<a href="https://colab.research.google.com/github/blessjal/blessjal/blob/main/2D_CNN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
def convolve2D(image, kernel1, kernel2, strides, padding=0):
  

    # Gather Shapes of Kernel + Image + Padding
    x1KernShape = kernel1.shape[0]
    y1KernShape = kernel1.shape[1]
    x2KernShape = kernel2.shape[0]
    y2KernShape = kernel2.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    x1Output = int(((xImgShape - x1KernShape + 2 * padding) / strides) + 1)
    y1Output = int(((yImgShape - y1KernShape + 2 * padding) / strides) + 1)
    x2Output = int(((xImgShape - x2KernShape + 2 * padding) / strides) + 1)
    y2Output = int(((yImgShape - y2KernShape + 2 * padding) / strides) + 1)
    output1 = np.zeros((x1Output, y1Output))
    output2 = np.zeros((x2Output, y2Output))


    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - y1KernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - x1KernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output1[x, y] = (kernel1*imagePadded[x: x + x1KernShape, y: y + y1KernShape]).sum()
                        output2[x, y] = (kernel2*imagePadded[x: x + x2KernShape, y: y + y2KernShape]).sum()
                except:
                    break

    print('output1:\n ',output1)
    print('output2: \n',output2)

In [45]:
import numpy as np

image = np.array([[1, 0, 0, 0, 0, 1], [0, 1, 0, 0, 1, 0], [0, 0, 1, 1, 0, 0], [1, 0, 0, 0, 1, 0], [0, 1, 0, 0, 1, 0], [0, 0, 1, 0, 1, 0]])

kernel1 = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
kernel2 = np.array([[-1, 1, -1], [-1, 1, -1], [-1, 1, -1]])

In [46]:
result = convolve2D(image=image, kernel1=kernel1, kernel2=kernel2, strides=1, padding=0)
result

output1:
  [[ 3. -1. -3. -1.]
 [-3.  1.  0. -3.]
 [-3. -3.  0.  1.]
 [ 3. -2. -2. -1.]]
output2: 
 [[-1. -1. -1. -1.]
 [-1. -1. -2.  1.]
 [-1. -1. -2.  1.]
 [-1.  0. -4.  3.]]


In [40]:
result2 = convolve2D(image=image, kernel1=kernel1, kernel2=kernel2, strides=3, padding=0)
result2

output1:
  [[3. 0.]
 [0. 0.]]
output2: 
 [[-1.  0.]
 [ 0.  0.]]


In [41]:
y1 = np.zeros((2, 2))
y2 = np.zeros((2, 2))

y1[0,0]=np.sum(image[0:3, 0:3]*kernel1)
y1[0,1]=np.sum(image[0:3, 3:6]*kernel1)
y1[1,0]=np.sum(image[3:6, 0:3]*kernel1)
y1[1,1]=np.sum(image[3:6,3:6]*kernel1)

y2[0,0]=np.sum(image[0:3, 0:3]*kernel2)
y2[0,1]=np.sum(image[0:3, 3:6]*kernel2)
y2[1,0]=np.sum(image[3:6, 0:3]*kernel2)
y2[1,1]=np.sum(image[3:6,3:6]*kernel2)
print('output1: \n', y1)
print()
print('ouput2: \n', y2)

output1: 
 [[ 3. -1.]
 [ 3. -1.]]

ouput2: 
 [[-1. -1.]
 [-1.  3.]]
